phpbb_ideas_index_controller:
    pattern: /ideas
    defaults: { _controller: phpbb.ideas.index_controller:index }

phpbb_ideas_idea_controller:
    pattern: /idea/{idea_id}
    defaults: { _controller: phpbb.ideas.idea_controller:idea }
    requirements:
        idea_id: \d+

phpbb_ideas_list_controller:
    pattern: /ideas/list/{sort}
    defaults: { _controller: phpbb.ideas.list_controller:ideas_list, sort: new }

phpbb_ideas_post_controller:
    pattern: /ideas/post
    defaults: { _controller: phpbb.ideas.post_controller:post }
