ideas_index_controller:
    pattern: /ideas
    defaults: { _controller: phpbb.ideas.controller:index }

ideas_idea_controller:
    pattern: /idea/{idea_id}
    defaults: { _controller: phpbb.ideas.controller:idea }

ideas_list_controller:
    pattern: /ideas/all/{sort}
    defaults: { _controller: phpbb.ideas.controller:all, sort: new }
