imports:
    - { resource: tables.yml }

services:
    phpbb.ideas.controller.base:
        abstract: true
        arguments:
            - @controller.helper
            - @template
            - @user
            - @phpbb.ideas.linkhelper
            - @phpbb.ideas.ideas
            - @request
            - %core.root_path%
            - %core.php_ext%

    phpbb.ideas.index_controller:
        class: phpbb\ideas\controller\index_controller
        parent: phpbb.ideas.controller.base

    phpbb.ideas.list_controller:
        class: phpbb\ideas\controller\list_controller
        parent: phpbb.ideas.controller.base

    phpbb.ideas.post_controller:
        class: phpbb\ideas\controller\post_controller
        parent: phpbb.ideas.controller.base

    phpbb.ideas.idea_controller:
        class: phpbb\ideas\controller\idea_controller
        arguments:
            - @auth
            - @cache
            - @config
            - @content.visibility
            - @dbal.conn
            - @controller.helper
            - @pagination
            - @profilefields.manager
            - @template
            - @user
            - @phpbb.ideas.linkhelper
            - @phpbb.ideas.ideas
            - @request
            - %core.root_path%
            - %core.php_ext%

    phpbb.ideas.ideas:
        class: phpbb\ideas\factory\ideas
        arguments:
            - @dbal.conn
            - @controller.helper
            - @log
            - @user
            - %tables.ideas_ideas%
            - %tables.ideas_duplicates%
            - %tables.ideas_rfcs%
            - %tables.ideas_statuses%
            - %tables.ideas_tickets%
            - %tables.ideas_votes%
            - %core.php_ext%

    phpbb.ideas.linkhelper:
        class: phpbb\ideas\factory\linkhelper
        arguments:
            - @controller.helper
            - @user_loader
